---
output: 
  html_document:
    keep_md: true
    self_contained: false
always_allow_html: yes
---

```{r, echo = FALSE}
load(file = "Data.RData")
```

```{r setup, include=FALSE}
library(lubridate)
library(plotly)
library(stringr)
library(plyr)
library(sp)
library(googleway)
library(webshot)
library(pander)
library(rpart)
knitr::opts_chunk$set(echo = TRUE)
load("Data.RData")
```
&nbsp;
&nbsp;
&nbsp;

  
## Week `r weekOfPlan` Advanced Statistics


### Steady State Workouts
```{r advancedStats, echo=FALSE, warning=FALSE}
plots <- htmltools::tagList()
gpsScores <- c()

RunningWeek <- RunningDataList[[weekOfPlan]]
SteadyRuns <- RunningWeek[RunningWeek$RunType == "Steady",]
for(i in 1:nrow(SteadyRuns)) {
  p <- plot_ly(SteadyRuns, height = 250, x = SteadyRuns$TimeStreams[[i]]/60, y = SteadyRuns$VelocityStreams[[i]], type = "scatter", mode = "lines", name = "Raw Data")
  smooth <- smooth.spline(SteadyRuns$TimeStreams[[i]]/60, SteadyRuns$VelocityStreams[[i]], spar = 1)
  smoothData <- data.frame(smooth$x, smooth$y)
  p <- p %>% add_trace(smoothData, x=smoothData$smooth.x, y=smoothData$smooth.y, name = 'Smoothened Data')
  p <- p %>% layout(title = paste("Steady State Run on", SteadyRuns$Date[[i]], "-", "Steady Score:", signif((1 - (1/(1+exp(-17* (sd(smoothData$smooth.y) -0.25))))) * 100, 2), "%"), xaxis = list(title = "Time (minutes)"), yaxis = list(title = "Speed (m/s)"), margin = list(t = 60, b = 40))
  plots[[i]] <- list(paste("GPS Score:", signif(100/(1 + exp(sum(diff(SteadyRuns$TimeStreams[[i]])^2)/SteadyRuns$TimeStreams[[i]][length(SteadyRuns$TimeStreams[[i]])] - 6)), 3)), "%", as_widget(p))
}
plots

```


```{r advancedTempoSetup, echo=FALSE, warning=FALSE}
plots <- htmltools::tagList()
intervals <- c()
TempoRuns <- RunningWeek[RunningWeek$RunType == "Tempo",]
numTempoRuns <- nrow(TempoRuns)
TempoString <- "Tempo Surge Workouts"
```

### `r if(numTempoRuns > 0) {TempoString}`
```{r advancedStatsTempo, echo=FALSE, warning=FALSE, results='asis'}
plots <- htmltools::tagList()
gpsScores <- c()

intervals <- c()
TempoRuns <- RunningWeek[RunningWeek$RunType == "Tempo",]
if(nrow(TempoRuns) > 0) {
for(i in 1:nrow(TempoRuns)) {
    tempoTimeStreams <- TempoRuns$TimeStreams[[i]]
    tempoVelocityStreams <- TempoRuns$VelocityStreams[[i]]
    tempoData <- data.frame(tempoTimeStreams, tempoVelocityStreams)
    p <- plot_ly(TempoRuns, height = 250, x = TempoRuns$TimeStreams[[i]]/60, y = TempoRuns$VelocityStreams[[i]], type = "scatter", mode = "lines", name = "Raw Data") %>% layout(title = paste("Tempo Run on", TempoRuns$Date[[i]]), xaxis = list(title = "Time (minutes)"), yaxis = list(title = "Speed (m/s)"))
    tree <- rpart(data = tempoData, formula = tempoVelocityStreams ~ tempoTimeStreams, control=rpart.control(cp = 0.05))
    s <- seq(0, max(tempoTimeStreams), by=.5)
    pieceWise <- data.frame(tempoTimeStreams, predict(tree, data.frame(tempoTimeStreams)))
    p <- p %>% add_trace(data = pieceWise, x = tempoTimeStreams/60, y = pieceWise$predict.tree..data.frame.tempoTimeStreams.., name = "Interval Fit")
    intervalPaces <- unique(1/(pieceWise$predict.tree..data.frame.tempoTimeStreams..) * (1000/60))
    intervalPaces <- paste(paste(paste(floor(intervalPaces), ":", str_pad(round((intervalPaces - floor(intervalPaces))*60), 2, pad = "0"), "/km", sep = ""), collapse = ", ", sep = ", "), sep = "")
    intervalPaces <- paste("Interval Paces:", intervalPaces, sep = " ")
    plots[[i]] <- list(p, intervalPaces, paste(cat(paste("  \nGPS Score:", signif(100/(1+exp(sum(diff(tempoTimeStreams)^2)/tempoTimeStreams[[length(tempoTimeStreams)]] - 6)),2)), "%")))
}
}
plots
```